### PR TITLE
MORTISE: Bootstrap mortise project

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
# Do Not Squash
This contains the code for the mortise project.  This code for `mortise.py` has all been reviewed in our private repo, so this is as we currently ship. 

The setup.py and readme are the parts that need a looking over.

### CODE REVIEW

**Comment by zsalzbank** [comment]
I'd make an examples directory and put the examples in there instead of having big chunks of code in the readme.

**Review by knitHacker — COMMENTED** [review]
Looks good to me.

**Comment by nickmarton** [comment]
`setup.py` looks good to me, though I suspect at some point you may wanna add the dependencies as they crop up (looks like there aren't any right now, but I'm sure at least numpy will make it in eventually). Agreed with Zach viz a viz having an examples directory instead of code in the README

**Comment by Jeff-Ciesielski** [comment]
> but I'm sure at least numpy will make it in eventually

I sincerely hope that we don't get to a point where our state machine library needs high performance math :|

**Comment by Jeff-Ciesielski** [comment]
Updated.

**Comment by knitHacker** [comment]
looks good to me

**Pull request merged**
