### PR TITLE
MORTISE: Bring in upstream timer handling changes

### PR DESCRIPTION
**Pull request by Jeff-Ciesielski**
Bringing in the latest upstream changes.

Given that we're at a pretty stable point, I'd like to make a formal release unless anyone objects?   

@keyme/robotics

### CODE REVIEW

**Comment by shonfeder** [comment]
These changes were already reviewed, right? Is it good form to get them a second review before merging downstream? Or is the only point to discuss here the formal release question (which is, of course, fine with me!)?

**Comment by Jeff-Ciesielski** [comment]
Making a PR just for the sake of following procedure.  This was already reviewed in the main repo.

Main point was to discuss thoughts on stability and if we want to make a formal release here and move to use this version and stop mirroring progress :)

**Comment by knitHacker** [comment]
lgtm but it was my PR

**Comment by Jeff-Ciesielski** [comment]
Alright.  Lets merge this in and get it released this week.

Lets discuss tomorrow the relative merits of submodules vs just installing this via pip.

**Pull request merged**
